//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json.Serialization;
using System;

public partial class Clients
{
    public long Client_ID { get; set; }

    [JsonPropertyName("FullName")]
    public string FIO { get; set; }

    [JsonPropertyName("E_mail")]
    public string Email { get; set; }

    [JsonPropertyName("BirthDate")]
    public Nullable<System.DateTime> BirthDate { get; set; }
}
